-- AlterTable
ALTER TABLE "Pricing" ADD COLUMN     "PremiumHourPrice" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ALTER COLUMN "baseFarePerKm" SET DEFAULT 1.0,
ALTER COLUMN "hourPrice" SET DEFAULT 10.0,
ALTER COLUMN "waitingHourPrice" SET DEFAULT 8.0,
ALTER COLUMN "discount" SET DEFAULT 0.0,
ALTER COLUMN "discountStartKm" SET DEFAULT 100.0,
ALTER COLUMN "oneTimeStartingFee" SET DEFAULT 70.0;
